- job:
    name: glance-secure-rbac-protection-functional
    parent: devstack-tempest
    timeout: 4200
    required-projects:
      - openstack/devstack-gate
      - openstack/glance
      - openstack/glance-tempest-plugin
    vars:
      tox_envlist: all
      tempest_test_regex: 'glance_tempest_plugin.tests.rbac'
      devstack_localrc:
        GLANCE_ENFORCE_SCOPE: True
        TEMPEST_PLUGINS: '/opt/stack/glance-tempest-plugin'
        USE_PYTHON3: True
      devstack_plugins:
        glance: https://opendev.org/openstack/glance
      devstack_local_conf:
        test-config:
          $GLANCE_API_CONF:
            DEFAULT:
              default_log_levels: "amqp=WARN, amqplib=WARN, boto=WARN, qpid=WARN, sqlalchemy=WARN, suds=INFO, oslo.messaging=INFO, oslo_messaging=INFO, iso8601=WARN, requests.packages.urllib3.connectionpool=WARN, urllib3.connectionpool=WARN, websocket=WARN, requests.packages.urllib3.util.retry=WARN, urllib3.util.retry=WARN, keystonemiddleware=WARN, routes.middleware=WARN, stevedore=WARN, taskflow=WARN, keystoneauth=WARN, oslo.cache=INFO, dogpile.core.dogpile=INFO, oslo_policy=DEBUG"

- job:
    name: glance-legacy-rbac-protection-functional
    parent: devstack-tempest
    timeout: 4200
    required-projects:
      - openstack/devstack-gate
      - openstack/glance
      - openstack/glance-tempest-plugin
    vars:
      tox_envlist: all
      tempest_test_regex: 'glance_tempest_plugin.tests.rbac.v2..*.Project(Admin|Member)Tests'
      devstack_localrc:
        TEMPEST_PLUGINS: '/opt/stack/glance-tempest-plugin'
        USE_PYTHON3: True
      devstack_plugins:
        glance: https://opendev.org/openstack/glance
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            image-feature-enabled:
              enforce_scope: true
          $GLANCE_API_CONF:
            DEFAULT:
              default_log_levels: "amqp=WARN, amqplib=WARN, boto=WARN, qpid=WARN, sqlalchemy=WARN, suds=INFO, oslo.messaging=INFO, oslo_messaging=INFO, iso8601=WARN, requests.packages.urllib3.connectionpool=WARN, urllib3.connectionpool=WARN, websocket=WARN, requests.packages.urllib3.util.retry=WARN, urllib3.util.retry=WARN, keystonemiddleware=WARN, routes.middleware=WARN, stevedore=WARN, taskflow=WARN, keystoneauth=WARN, oslo.cache=INFO, dogpile.core.dogpile=INFO, oslo_policy=DEBUG"

- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - glance-secure-rbac-protection-functional:
            voting: false
        - glance-legacy-rbac-protection-functional
    gate:
      jobs:
        - glance-secure-rbac-protection-functional:
            voting: false
        - glance-legacy-rbac-protection-functional
